package com.model.pojo;
// Generated May 21, 2020 1:52:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java 
 */
@Entity
@Table(name="user"
    ,catalog="plazza"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String sex;
     private String data_de_nascimento;
     private String email;
     private String username;
     private String password;

    public User() {
    }

    public User(String name, String surname, String data_de_nascimento, String sex, String email) {
       this.name = name;
       this.surname = surname;
       this.sex = sex;
       this.data_de_nascimento=data_de_nascimento;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Name", length=100)
    public String getName() {
        return this.name;
    }
    
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
     
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="data_de_nascimento", length=20)
    public String getData_de_nascimento() {
        return this.data_de_nascimento;
    }
    
    public void setData_de_nascimento(String data_de_nascimento) {
        this.data_de_nascimento=data_de_nascimento;
    }

    
    @Column(name="Sex", length=20)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

}


